# CURE-Rec — behavioral calibration robustness

This notebook runs the **pre-specified CURE-Sim assumption-sensitivity study** after the final BPR archive is frozen. It does not use MovieLens to calibrate causal effects and it does not tune the recommendation model.

Each enabled run recomputes the exact six-player game for every configuration and seed. Leave all execution guards `False` until you deliberately want that cost.

## 1. Setup

Run after `git pull` and a kernel restart. The cell resolves the CURE-Rec source directory from either the repository root or the code directory.

In [1]:
from pathlib import Path
import importlib
import json
import sys
import pandas as pd

CWD = Path.cwd().resolve()
CANDIDATES = [CWD, CWD / 'paper-ideas' / 'CURE-Rec' / 'code', *CWD.parents]
ROOT = next((p for p in CANDIDATES if (p / 'pyproject.toml').exists() and (p / 'cure_rec').exists()), None)
if ROOT is None:
    raise RuntimeError('Open this notebook from the CURE-Rec code directory or repository root.')
sys.path[:] = [str(ROOT), *[item for item in sys.path if item != str(ROOT)]]
for name in list(sys.modules):
    if name == 'cure_rec' or name.startswith('cure_rec.'):
        del sys.modules[name]
importlib.invalidate_caches()

from cure_rec.calibration import run_calibration_sweep
from cure_rec.config import load_settings

QUICK_CONFIG = ROOT / 'configs' / 'curesim_quickstart.yaml'
FULL_CONFIG = ROOT / 'configs' / 'curesim_full.yaml'
RUN_ROOT = ROOT / 'runs'
print('CURE-Rec source:', ROOT)

CURE-Rec source: /Users/mlouhichi/Desktop/CURE-Rec/next-paper/paper-ideas/CURE-Rec/code

## 2. Read this before enabling a run

- **OAT** runs one frozen baseline and two predeclared contrast values for each of seven assumptions: 15 configurations total.
- **LHS** runs one frozen baseline plus the requested number of joint Latin-hypercube configurations.
- Each configuration is repeated over the stated independent environment seeds and evaluates all 64 coalitions in every configured scenario.
- Neither design selects a best configuration. All seed-level results, feasibility outcomes, planner modes, attributions, and interactions are retained.

In [11]:
RUN_CALIBRATION_SMOKE = False
RUN_CALIBRATION_OAT_FULL = False
RUN_CALIBRATION_LHS_FULL = True

CALIBRATION_RESUME_DIR = None

## 3. Action 1 — cheap structural smoke run

This is still an exact-game run, but uses the quick simulator, one seed, and one LHS configuration plus the baseline. It verifies output tables/figures before the full study.

In [8]:
if RUN_CALIBRATION_SMOKE:
    smoke = load_settings(QUICK_CONFIG)
    smoke.run.name = 'calibration-smoke'
    smoke.run.output_root = RUN_ROOT
    smoke_result = run_calibration_sweep(smoke, seeds=(42,), design='lhs', lhs_samples=1)
    print('Smoke calibration:', smoke_result.run_dir)
    display(smoke_result.summary)
else:
    print('Smoke calibration disabled.')

Smoke calibration disabled.

## 4. Action 2 — full one-at-a-time phase diagram

This is the interpretable primary sensitivity analysis. It evaluates 15 configurations × 5 seeds under the full four-scenario CURE-Sim configuration. It checkpoints completed point-level aggregates and can resume after a shutdown. To resume an interrupted run, set `CALIBRATION_RESUME_DIR` in the guard cell; completed child seeds are recovered and are not rerun.

In [7]:
if RUN_CALIBRATION_OAT_FULL:
    full = load_settings(FULL_CONFIG)
    full.run.name = 'calibration-oat-full'
    full.run.output_root = RUN_ROOT
    oat_result = run_calibration_sweep(full, seeds=FULL_SEEDS, design='oat', resume_dir=CALIBRATION_RESUME_DIR)
    print('Full OAT calibration:', oat_result.run_dir)
    display(oat_result.summary)
else:
    print('Full OAT calibration disabled.')

2026-08-06 14:18:57,454 | INFO | run_started | {"config_hash": "8f50e9250a7573aa", "run_id": "calibration-oat-provider_threshold-0p3200-seed-46-20260806T131857Z-c092d17b"}
2026-08-06 14:18:57,454 | INFO | exact_game_started | {}
2026-08-06 14:18:57,455 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "nominal"}
2026-08-06 14:21:37,864 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13812789327397867, "scenario": "nominal", "shapley_efficiency_gap": 0.0}
2026-08-06 14:21:37,865 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "fatigue_stress"}
2026-08-06 14:24:16,499 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13526674777644043, "scenario": "fatigue_stress", "shapley_efficiency_gap": 8.326672684688674e-17}
2026-08-06 14:24:16,500 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "popularity_stress"}
2026-08-06 14:26:55,135 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.14751529178466882, "scenario": "popularity_stress", "shapley_efficiency_gap": -2.7755575615628914e-17}
2026-08-06 14:26:55,136 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "mixed_stress"}
2026-08-06 14:29:33,921 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.1527835545805119, "scenario": "mixed_stress", "shapley_efficiency_gap": -5.551115123125783e-17}
2026-08-06 14:29:33,926 | INFO | exact_game_completed | {"duration_seconds": 636.4901504579998}
2026-08-06 14:29:33,927 | INFO | robust_planning_started | {}
2026-08-06 14:29:33,927 | INFO | planner_mode_resolved | {"base_feasible": true, "base_lower_improvement": 0.0, "cost": 0.0, "fatigue_upper": 0.49276204845491933, "mode": "improvement", "provider_disparity_upper": 0.2959104938271604, "relevance_delta_lower": 0.0}
2026-08-06 14:29:33,927 | INFO | portfolio_rejected | {"active_interventions": ["diversify"], "coalition_mask": 8, "cost": 0.06, "fatigue_upper": 0.49064264982584843, "lower_improvement": -0.05938667035026157, "mode": "improvement", "provider_disparity_upper": 0.33060185185185187, "relevance_delta_lower": -0.004315183172159953}
2026-08-06 14:29:33,928 | INFO | portfolio_rejected | {"active_interventions": ["novel_slot"], "coalition_mask": 16, "cost": 0.08, "fatigue_upper": 0.4610338511653522, "lower_improvement": -0.07379817003241113, "mode": "improvement", "provider_disparity_upper": 0.37717592592592597, "relevance_delta_lower": -0.03599169768790078}
2026-08-06 14:29:33,928 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "novel_slot"], "coalition_mask": 18, "cost": 0.18, "fatigue_upper": 0.42109682721105474, "lower_improvement": -0.14175676774413432, "mode": "improvement", "provider_disparity_upper": 0.36058641975308636, "relevance_delta_lower": -0.03738746692342021}
2026-08-06 14:29:33,929 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "novel_slot"], "coalition_mask": 20, "cost": 0.16, "fatigue_upper": 0.42533816614575637, "lower_improvement": -0.12234144808471836, "mode": "improvement", "provider_disparity_upper": 0.36402777777777784, "relevance_delta_lower": -0.03507641057001443}
2026-08-06 14:29:33,929 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot"], "coalition_mask": 22, "cost": 0.26, "fatigue_upper": 0.41945906318310433, "lower_improvement": -0.2137920802174622, "mode": "improvement", "provider_disparity_upper": 0.3213194444444445, "relevance_delta_lower": -0.03419439745243058}
2026-08-06 14:29:33,929 | INFO | portfolio_rejected | {"active_interventions": ["diversify", "novel_slot"], "coalition_mask": 24, "cost": 0.14, "fatigue_upper": 0.46578350088920045, "lower_improvement": -0.13062756560881728, "mode": "improvement", "provider_disparity_upper": 0.38262345679012344, "relevance_delta_lower": -0.024337278220041725}
2026-08-06 14:29:33,930 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot"], "coalition_mask": 26, "cost": 0.24, "fatigue_upper": 0.4285604192068518, "lower_improvement": -0.20410979174840455, "mode": "improvement", "provider_disparity_upper": 0.36165123456790127, "relevance_delta_lower": -0.03020577037095651}
2026-08-06 14:29:33,930 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify", "novel_slot"], "coalition_mask": 28, "cost": 0.22, "fatigue_upper": 0.4345749374634345, "lower_improvement": -0.1875884557959903, "mode": "improvement", "provider_disparity_upper": 0.3815432098765432, "relevance_delta_lower": -0.028730327568190717}
2026-08-06 14:29:33,930 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 30, "cost": 0.32, "fatigue_upper": 0.4329701196349142, "lower_improvement": -0.2812582930588101, "mode": "improvement", "provider_disparity_upper": 0.3381327160493828, "relevance_delta_lower": -0.027602163152057324}
2026-08-06 14:29:33,931 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 31, "cost": 0.37, "fatigue_upper": 0.0, "lower_improvement": -0.03350868270722002, "mode": "improvement", "provider_disparity_upper": 0.2124228395061729, "relevance_delta_lower": -0.04449939740447251}
2026-08-06 14:29:33,931 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 46, "cost": 0.36, "fatigue_upper": 0.4377267344790385, "lower_improvement": -0.3167921297237268, "mode": "improvement", "provider_disparity_upper": 0.07667438271604943, "relevance_delta_lower": -0.003947199361834852}
2026-08-06 14:29:33,931 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 47, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.06430645447001898, "mode": "improvement", "provider_disparity_upper": 0.11547067901234565, "relevance_delta_lower": -0.03706945174543996}
2026-08-06 14:29:33,932 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 54, "cost": 0.38, "fatigue_upper": 0.4412204291136819, "lower_improvement": -0.34614674724731487, "mode": "improvement", "provider_disparity_upper": 0.10271604938271595, "relevance_delta_lower": -0.016125929536671357}
2026-08-06 14:29:33,932 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 55, "cost": 0.43, "fatigue_upper": 0.0, "lower_improvement": -0.09506364307299497, "mode": "improvement", "provider_disparity_upper": 0.11037037037037045, "relevance_delta_lower": -0.04679329112646469}
2026-08-06 14:29:33,932 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 58, "cost": 0.36, "fatigue_upper": 0.4377602460003857, "lower_improvement": -0.32304372364800127, "mode": "improvement", "provider_disparity_upper": 0.08295524691358014, "relevance_delta_lower": -0.016259910262274913}
2026-08-06 14:29:33,933 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 59, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.07424700871548323, "mode": "improvement", "provider_disparity_upper": 0.106604938271605, "relevance_delta_lower": -0.04634649671362723}
2026-08-06 14:29:33,933 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 61, "cost": 0.39, "fatigue_upper": 0.0, "lower_improvement": -0.05419013331708805, "mode": "improvement", "provider_disparity_upper": 0.11808641975308642, "relevance_delta_lower": -0.04538081532236016}
2026-08-06 14:29:33,933 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 62, "cost": 0.44, "fatigue_upper": 0.44150253998724354, "lower_improvement": -0.4025608925793788, "mode": "improvement", "provider_disparity_upper": 0.08766203703703712, "relevance_delta_lower": -0.011713350619391827}
2026-08-06 14:29:33,934 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 63, "cost": 0.49, "fatigue_upper": 0.0, "lower_improvement": -0.1527835545805119, "mode": "improvement", "provider_disparity_upper": 0.11058641975308636, "relevance_delta_lower": -0.04330917208665008}
2026-08-06 14:29:33,934 | INFO | portfolio_selected | {"action": "improve_selected", "base_feasible": true, "cost": 0.05, "fatigue_upper": 0.0, "feasible": true, "lower_improvement": 0.293002483007298, "mode": "improvement", "provider_disparity_upper": 0.21988425925925914, "reason": "Base policy is feasible; selected the exact maximin-improvement portfolio.", "relevance_delta_lower": -0.036125545165068274, "selected_interventions": ["repeat_cap"], "selected_mask": 1, "status": "improve_selected", "upper_improvement": 0.3109411815143742}
2026-08-06 14:29:33,936 | INFO | explanation_card_written | {"selected_mask": 1, "status": "improve_selected"}
2026-08-06 14:29:33,936 | INFO | robust_planning_completed | {"duration_seconds": 0.009314207999977953}
2026-08-06 14:29:33,936 | INFO | reporting_started | {}
2026-08-06 14:29:34,366 | INFO | assets_generated | {"figures": ["figures/figure_01_framework.png", "figures/figure_02_shapley_regions.png", "figures/figure_03_uncertainty_widths.png", "figures/figure_04_interaction_heatmap.png", "figures/figure_05_trajectory_comparison.png", "figures/figure_06_decision_card.png", "figures/figure_07_runtime_by_cardinality.png", "figures/figure_08_scenario_sensitivity.png"], "tables": ["tables/table_01_asset_registry.csv", "tables/table_02_benchmark_configuration.csv", "tables/table_03_attribution_regions.csv", "tables/table_04_uncertainty_summary.csv", "tables/table_05_portfolio_decision.csv", "tables/table_06_long_term_tradeoffs.csv", "tables/table_07_selection_comparison.csv", "tables/table_08_runtime_summary.csv"]}
2026-08-06 14:29:34,367 | INFO | reporting_completed | {"duration_seconds": 0.4309729999999945}
2026-08-06 14:29:34,367 | INFO | run_finished | {"run_dir": "/Users/mlouhichi/Desktop/CURE-Rec/next-paper/paper-ideas/CURE-Rec/code/runs/calibration-oat-20260805T184133Z/oat-provider_threshold-0p3200/seed-sweep-20260806T131857Z/runs/calibration-oat-provider_threshold-0p3200-seed-46-20260806T131857Z-c092d17b", "status": "completed"}
2026-08-06 14:29:34,569 | INFO | run_started | {"config_hash": "a8e93f2aecddf4ef", "run_id": "calibration-oat-provider_balance_strength-0p1500-seed-42-20260806T132934Z-b6c111c7"}
2026-08-06 14:29:34,569 | INFO | exact_game_started | {}
2026-08-06 14:29:34,570 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "nominal"}
2026-08-06 14:32:14,609 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13762341074231632, "scenario": "nominal", "shapley_efficiency_gap": -2.7755575615628914e-17}
2026-08-06 14:32:14,610 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "fatigue_stress"}
2026-08-06 14:34:54,115 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.1327428341318892, "scenario": "fatigue_stress", "shapley_efficiency_gap": 0.0}
2026-08-06 14:34:54,116 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "popularity_stress"}
2026-08-06 14:37:33,553 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.14488827064337595, "scenario": "popularity_stress", "shapley_efficiency_gap": 5.551115123125783e-17}
2026-08-06 14:37:33,553 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "mixed_stress"}
2026-08-06 14:40:13,027 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.14387129357392614, "scenario": "mixed_stress", "shapley_efficiency_gap": 5.551115123125783e-17}
2026-08-06 14:40:13,032 | INFO | exact_game_completed | {"duration_seconds": 638.4425960000003}
2026-08-06 14:40:13,032 | INFO | robust_planning_started | {}
2026-08-06 14:40:13,033 | INFO | planner_mode_resolved | {"base_feasible": false, "base_lower_improvement": 0.0, "cost": 0.0, "fatigue_upper": 0.492758111834193, "mode": "repair", "provider_disparity_upper": 0.3277854938271605, "relevance_delta_lower": 0.0}
2026-08-06 14:40:13,033 | INFO | portfolio_rejected | {"active_interventions": [], "coalition_mask": 0, "cost": 0.0, "fatigue_upper": 0.492758111834193, "lower_improvement": 0.0, "mode": "repair", "provider_disparity_upper": 0.3277854938271605, "relevance_delta_lower": 0.0}
2026-08-06 14:40:13,033 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot"], "coalition_mask": 2, "cost": 0.1, "fatigue_upper": 0.45869019290566704, "lower_improvement": -0.0718960331907077, "mode": "repair", "provider_disparity_upper": 0.3049845679012346, "relevance_delta_lower": -0.007799518670424943}
2026-08-06 14:40:13,034 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot"], "coalition_mask": 4, "cost": 0.08, "fatigue_upper": 0.45901818722079935, "lower_improvement": -0.05145415155627292, "mode": "repair", "provider_disparity_upper": 0.2931018518518518, "relevance_delta_lower": -0.006369554561711843}
2026-08-06 14:40:13,034 | INFO | portfolio_rejected | {"active_interventions": ["diversify"], "coalition_mask": 8, "cost": 0.06, "fatigue_upper": 0.48961044133949305, "lower_improvement": -0.058702188418542245, "mode": "repair", "provider_disparity_upper": 0.3236419753086419, "relevance_delta_lower": -0.005079540350818257}
2026-08-06 14:40:13,034 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify"], "coalition_mask": 10, "cost": 0.16, "fatigue_upper": 0.4645983039226619, "lower_improvement": -0.13806072448302606, "mode": "repair", "provider_disparity_upper": 0.317199074074074, "relevance_delta_lower": -0.008243106079063978}
2026-08-06 14:40:13,035 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify"], "coalition_mask": 12, "cost": 0.14, "fatigue_upper": 0.4683996345990081, "lower_improvement": -0.11933190823552803, "mode": "repair", "provider_disparity_upper": 0.29574074074074064, "relevance_delta_lower": -0.008019049556712066}
2026-08-06 14:40:13,035 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify"], "coalition_mask": 14, "cost": 0.24, "fatigue_upper": 0.4333103533473186, "lower_improvement": -0.19234569115815603, "mode": "repair", "provider_disparity_upper": 0.2911574074074075, "relevance_delta_lower": -0.014116450565537342}
2026-08-06 14:40:13,035 | INFO | portfolio_rejected | {"active_interventions": ["novel_slot"], "coalition_mask": 16, "cost": 0.08, "fatigue_upper": 0.4708963318136204, "lower_improvement": -0.07967326109937028, "mode": "repair", "provider_disparity_upper": 0.4050694444444445, "relevance_delta_lower": -0.025534290377414837}
2026-08-06 14:40:13,036 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "novel_slot"], "coalition_mask": 17, "cost": 0.13, "fatigue_upper": 0.0, "lower_improvement": 0.20362481361283913, "mode": "repair", "provider_disparity_upper": 0.28248456790123444, "relevance_delta_lower": -0.060886430305401196}
2026-08-06 14:40:13,036 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "novel_slot"], "coalition_mask": 18, "cost": 0.18, "fatigue_upper": 0.4299919455947753, "lower_improvement": -0.14821801131279988, "mode": "repair", "provider_disparity_upper": 0.3733564814814814, "relevance_delta_lower": -0.03161334958642281}
2026-08-06 14:40:13,036 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "novel_slot"], "coalition_mask": 20, "cost": 0.16, "fatigue_upper": 0.43204314842271185, "lower_improvement": -0.12663574928439855, "mode": "repair", "provider_disparity_upper": 0.36898148148148135, "relevance_delta_lower": -0.028120548903493692}
2026-08-06 14:40:13,037 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot"], "coalition_mask": 22, "cost": 0.26, "fatigue_upper": 0.428650551451011, "lower_improvement": -0.22192326600730616, "mode": "repair", "provider_disparity_upper": 0.3564583333333333, "relevance_delta_lower": -0.02745259931776689}
2026-08-06 14:40:13,037 | INFO | portfolio_rejected | {"active_interventions": ["diversify", "novel_slot"], "coalition_mask": 24, "cost": 0.14, "fatigue_upper": 0.46972888786066547, "lower_improvement": -0.136647037274358, "mode": "repair", "provider_disparity_upper": 0.3825694444444445, "relevance_delta_lower": -0.01902584481018088}
2026-08-06 14:40:13,037 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot"], "coalition_mask": 26, "cost": 0.24, "fatigue_upper": 0.43950350851425496, "lower_improvement": -0.213128011246626, "mode": "repair", "provider_disparity_upper": 0.35524691358024696, "relevance_delta_lower": -0.02372951401421375}
2026-08-06 14:40:13,038 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify", "novel_slot"], "coalition_mask": 28, "cost": 0.22, "fatigue_upper": 0.4434807030025221, "lower_improvement": -0.19867176065770323, "mode": "repair", "provider_disparity_upper": 0.37247685185185175, "relevance_delta_lower": -0.026135889458932637}
2026-08-06 14:40:13,038 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 30, "cost": 0.32, "fatigue_upper": 0.4382154896894196, "lower_improvement": -0.28880694210414176, "mode": "repair", "provider_disparity_upper": 0.34087191358024693, "relevance_delta_lower": -0.020471738817110063}
2026-08-06 14:40:13,038 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 31, "cost": 0.37, "fatigue_upper": 0.0, "lower_improvement": -0.026028341085559514, "mode": "repair", "provider_disparity_upper": 0.2150154320987654, "relevance_delta_lower": -0.04768507760083063}
2026-08-06 14:40:13,039 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 46, "cost": 0.36, "fatigue_upper": 0.4349168015717942, "lower_improvement": -0.3100409108527724, "mode": "repair", "provider_disparity_upper": 0.1751466049382715, "relevance_delta_lower": -0.010361226476748975}
2026-08-06 14:40:13,039 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 47, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.05838693328500466, "mode": "repair", "provider_disparity_upper": 0.14831018518518513, "relevance_delta_lower": -0.044498858803689534}
2026-08-06 14:40:13,039 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 54, "cost": 0.38, "fatigue_upper": 0.44573643093683984, "lower_improvement": -0.3490383693756172, "mode": "repair", "provider_disparity_upper": 0.23593364197530864, "relevance_delta_lower": -0.021407223759773997}

,point_id,varied_parameter,varied_value,is_baseline,seed_count,selected_portfolio_mode,selected_portfolio_mode_frequency,selection_stability,repeat_cap_selection_rate,base_feasibility_rate,...,fatigue_upper_mean,config_hash,recovered_seed_count,parameter_fatigue_strength,parameter_repeat_threshold,parameter_horizon,parameter_provider_threshold,parameter_provider_balance_strength,parameter_novelty_delayed_benefit,parameter_exploration_cost
0,baseline,baseline,NaN,True,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,9798e91ec7ada5f2,5,1.00,3,12,0.28,0.35,0.00,0.10
1,oat-fatigue_strength-0p7500,fatigue_strength,0.75,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,aad136c8858c57bf,5,0.75,3,12,0.28,0.35,0.00,0.10
2,oat-fatigue_strength-1p2500,fatigue_strength,1.25,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,23b22ca44e5e1491,5,1.25,3,12,0.28,0.35,0.00,0.10
3,oat-repeat_threshold-2,repeat_threshold,2.00,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.262137,0e8c4922cb348567,5,1.00,2,12,0.28,0.35,0.00,0.10
4,oat-repeat_threshold-4,repeat_threshold,4.00,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,409a3894e128ae19,5,1.00,4,12,0.28,0.35,0.00,0.10
5,oat-horizon-8,horizon,8.00,False,5,"('repeat_cap',)",5,1.0,1.0,0.6,...,0.000000,3dfc6af2b625c550,5,1.00,3,8,0.28,0.35,0.00,0.10
6,oat-horizon-16,horizon,16.00,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,cdfbd1be96de4893,5,1.00,3,16,0.28,0.35,0.00,0.10
7,oat-provider_threshold-0p2400,provider_threshold,0.24,False,5,"('repeat_cap',)",4,0.8,1.0,0.0,...,0.000000,7796d9c704e67468,5,1.00,3,12,0.24,0.35,0.00,0.10
8,oat-provider_threshold-0p3200,provider_threshold,0.32,False,5,"('repeat_cap',)",5,1.0,1.0,0.6,...,0.000000,7b1e304238e1cae7,5,1.00,3,12,0.32,0.35,0.00,0.10
9,oat-provider_balance_strength-0p1500,provider_balance_strength,0.15,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,658db72cd92964cf,5,1.00,3,12,0.28,0.15,0.00,0.10
10,oat-provider_balance_strength-0p5500,provider_balance_strength,0.55,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,21c3770675721213,5,1.00,3,12,0.28,0.55,0.00,0.10
11,oat-novelty_delayed_benefit-0p0300,novelty_delayed_benefit,0.03,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,a3c275a65d844cc7,5,1.00,3,12,0.28,0.35,0.03,0.10
12,oat-novelty_delayed_benefit-0p0600,novelty_delayed_benefit,0.06,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,4c4f5115137005f7,5,1.00,3,12,0.28,0.35,0.06,0.10
13,oat-exploration_cost-0p0500,exploration_cost,0.05,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,acdbadfb6d3ff042,5,1.00,3,12,0.28,0.35,0.00,0.05
14,oat-exploration_cost-0p1500,exploration_cost,0.15,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,9d20c8c4af21855f,5,1.00,3,12,0.28,0.35,0.00,0.15

## 5. Action 3 — joint Latin-hypercube robustness probe

Run only after the OAT phase diagram has completed. This examines joint assumptions rather than picking a favorable setting. With `LHS_SAMPLES = 24`, it evaluates 25 configurations (including the baseline) × 5 seeds.

In [12]:
if RUN_CALIBRATION_LHS_FULL:
    full = load_settings(FULL_CONFIG)
    full.run.name = 'calibration-lhs-full'
    full.run.output_root = RUN_ROOT
    lhs_result = run_calibration_sweep(full, seeds=FULL_SEEDS, design='lhs', lhs_samples=LHS_SAMPLES, resume_dir=CALIBRATION_RESUME_DIR)
    print('Full LHS calibration:', lhs_result.run_dir)
    display(lhs_result.summary)
else:
    print('Full LHS calibration disabled.')

2026-08-06 20:54:46,771 | INFO | run_started | {"config_hash": "f069f4f0ed51dcaf", "run_id": "calibration-baseline-seed-42-20260806T195446Z-a7ee83c5"}
2026-08-06 20:54:46,772 | INFO | exact_game_started | {}
2026-08-06 20:54:46,773 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "nominal"}
2026-08-06 20:57:29,636 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13710546477148466, "scenario": "nominal", "shapley_efficiency_gap": 0.0}
2026-08-06 20:57:29,637 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "fatigue_stress"}
2026-08-06 21:00:11,939 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13194331906701645, "scenario": "fatigue_stress", "shapley_efficiency_gap": 2.7755575615628914e-17}
2026-08-06 21:00:11,940 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "popularity_stress"}
2026-08-06 21:02:54,353 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.1442994774717976, "scenario": "popularity_stress", "shapley_efficiency_gap": -5.551115123125783e-17}
2026-08-06 21:02:54,355 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "mixed_stress"}
2026-08-06 21:05:36,367 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.1439196583329556, "scenario": "mixed_stress", "shapley_efficiency_gap": 0.0}
2026-08-06 21:05:36,375 | INFO | exact_game_completed | {"duration_seconds": 649.5709542090008}
2026-08-06 21:05:36,376 | INFO | robust_planning_started | {}
2026-08-06 21:05:36,377 | INFO | planner_mode_resolved | {"base_feasible": false, "base_lower_improvement": 0.0, "cost": 0.0, "fatigue_upper": 0.492758111834193, "mode": "repair", "provider_disparity_upper": 0.3277854938271605, "relevance_delta_lower": 0.0}
2026-08-06 21:05:36,377 | INFO | portfolio_rejected | {"active_interventions": [], "coalition_mask": 0, "cost": 0.0, "fatigue_upper": 0.492758111834193, "lower_improvement": 0.0, "mode": "repair", "provider_disparity_upper": 0.3277854938271605, "relevance_delta_lower": 0.0}
2026-08-06 21:05:36,378 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot"], "coalition_mask": 2, "cost": 0.1, "fatigue_upper": 0.45869019290566704, "lower_improvement": -0.0718960331907077, "mode": "repair", "provider_disparity_upper": 0.3049845679012346, "relevance_delta_lower": -0.007799518670424943}
2026-08-06 21:05:36,378 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot"], "coalition_mask": 4, "cost": 0.08, "fatigue_upper": 0.45901818722079935, "lower_improvement": -0.05145415155627292, "mode": "repair", "provider_disparity_upper": 0.2931018518518518, "relevance_delta_lower": -0.006369554561711843}
2026-08-06 21:05:36,378 | INFO | portfolio_rejected | {"active_interventions": ["diversify"], "coalition_mask": 8, "cost": 0.06, "fatigue_upper": 0.48961044133949305, "lower_improvement": -0.058702188418542245, "mode": "repair", "provider_disparity_upper": 0.3236419753086419, "relevance_delta_lower": -0.005079540350818257}
2026-08-06 21:05:36,379 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify"], "coalition_mask": 10, "cost": 0.16, "fatigue_upper": 0.4645983039226619, "lower_improvement": -0.13806072448302606, "mode": "repair", "provider_disparity_upper": 0.317199074074074, "relevance_delta_lower": -0.008243106079063978}
2026-08-06 21:05:36,379 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify"], "coalition_mask": 12, "cost": 0.14, "fatigue_upper": 0.4683996345990081, "lower_improvement": -0.11933190823552803, "mode": "repair", "provider_disparity_upper": 0.29574074074074064, "relevance_delta_lower": -0.008019049556712066}
2026-08-06 21:05:36,380 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify"], "coalition_mask": 14, "cost": 0.24, "fatigue_upper": 0.4333103533473186, "lower_improvement": -0.19234569115815603, "mode": "repair", "provider_disparity_upper": 0.2911574074074075, "relevance_delta_lower": -0.014116450565537342}
2026-08-06 21:05:36,380 | INFO | portfolio_rejected | {"active_interventions": ["novel_slot"], "coalition_mask": 16, "cost": 0.08, "fatigue_upper": 0.4708963318136204, "lower_improvement": -0.07967326109937028, "mode": "repair", "provider_disparity_upper": 0.4050694444444445, "relevance_delta_lower": -0.025534290377414837}
2026-08-06 21:05:36,381 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "novel_slot"], "coalition_mask": 17, "cost": 0.13, "fatigue_upper": 0.0, "lower_improvement": 0.20362481361283913, "mode": "repair", "provider_disparity_upper": 0.28248456790123444, "relevance_delta_lower": -0.060886430305401196}
2026-08-06 21:05:36,381 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "novel_slot"], "coalition_mask": 18, "cost": 0.18, "fatigue_upper": 0.4299919455947753, "lower_improvement": -0.14821801131279988, "mode": "repair", "provider_disparity_upper": 0.3733564814814814, "relevance_delta_lower": -0.03161334958642281}
2026-08-06 21:05:36,381 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "novel_slot"], "coalition_mask": 20, "cost": 0.16, "fatigue_upper": 0.43204314842271185, "lower_improvement": -0.12663574928439855, "mode": "repair", "provider_disparity_upper": 0.36898148148148135, "relevance_delta_lower": -0.028120548903493692}
2026-08-06 21:05:36,382 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot"], "coalition_mask": 22, "cost": 0.26, "fatigue_upper": 0.428650551451011, "lower_improvement": -0.22192326600730616, "mode": "repair", "provider_disparity_upper": 0.3564583333333333, "relevance_delta_lower": -0.02745259931776689}
2026-08-06 21:05:36,382 | INFO | portfolio_rejected | {"active_interventions": ["diversify", "novel_slot"], "coalition_mask": 24, "cost": 0.14, "fatigue_upper": 0.46972888786066547, "lower_improvement": -0.136647037274358, "mode": "repair", "provider_disparity_upper": 0.3825694444444445, "relevance_delta_lower": -0.01902584481018088}
2026-08-06 21:05:36,383 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot"], "coalition_mask": 26, "cost": 0.24, "fatigue_upper": 0.43950350851425496, "lower_improvement": -0.213128011246626, "mode": "repair", "provider_disparity_upper": 0.35524691358024696, "relevance_delta_lower": -0.02372951401421375}
2026-08-06 21:05:36,383 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify", "novel_slot"], "coalition_mask": 28, "cost": 0.22, "fatigue_upper": 0.4434807030025221, "lower_improvement": -0.19867176065770323, "mode": "repair", "provider_disparity_upper": 0.37247685185185175, "relevance_delta_lower": -0.026135889458932637}
2026-08-06 21:05:36,383 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 30, "cost": 0.32, "fatigue_upper": 0.4382154896894196, "lower_improvement": -0.28880694210414176, "mode": "repair", "provider_disparity_upper": 0.34087191358024693, "relevance_delta_lower": -0.020471738817110063}
2026-08-06 21:05:36,383 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 31, "cost": 0.37, "fatigue_upper": 0.0, "lower_improvement": -0.026028341085559514, "mode": "repair", "provider_disparity_upper": 0.2150154320987654, "relevance_delta_lower": -0.04768507760083063}
2026-08-06 21:05:36,384 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 46, "cost": 0.36, "fatigue_upper": 0.4402105418990686, "lower_improvement": -0.3150380522162787, "mode": "repair", "provider_disparity_upper": 0.09385802469135807, "relevance_delta_lower": -0.009180726174821796}
2026-08-06 21:05:36,384 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 47, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.058618580237987494, "mode": "repair", "provider_disparity_upper": 0.10016975308641962, "relevance_delta_lower": -0.04659057023172486}
2026-08-06 21:05:36,385 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 54, "cost": 0.38, "fatigue_upper": 0.44827228489318643, "lower_improvement": -0.3510557086220646, "mode": "repair", "provider_disparity_upper": 0.1276311728395061, "relevance_delta_lower": -0.01917580489955728}
2026-08-06 21:05:36,385 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 55, "cost": 0.43, "fatigue_upper": 0.0, "lower_improvement": -0.08571605117743603, "mode": "repair", "provider_disparity_upper": 0.10063271604938273, "relevance_delta_lower": -0.04977195147468261}
2026-08-06 21:05:36,385 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 58, "cost": 0.36, "fatigue_upper": 0.4410881927265759, "lower_improvement": -0.32638713704700373, "mode": "repair", "provider_disparity_upper": 0.104837962962963, "relevance_delta_lower": -0.01797192636254663}
2026-08-06 21:05:36,386 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 59, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.06785257426425684, "mode": "repair", "provider_disparity_upper": 0.10189814814814802, "relevance_delta_lower": -0.05170810325278663}
2026-08-06 21:05:36,386 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 61, "cost": 0.39, "fatigue_upper": 0.0, "lower_improvement": -0.04746354259630148, "mode": "repair", "provider_disparity_upper": 0.10492283950617276, "relevance_delta_lower": -0.0537989025697293}
2026-08-06 21:05:36,386 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 62, "cost": 0.44, "fatigue_upper": 0.4491607010993689, "lower_improvement": -0.40754665847123517, "mode": "repair", "provider_disparity_upper": 0.10325617283950606, "relevance_delta_lower": -0.01478150102028608}
2026-08-06 21:05:36,387 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 63, "cost": 0.49, "fatigue_upper": 0.0, "lower_improvement": -0.1442994774717976, "mode": "repair", "provider_disparity_upper": 0.09958333333333336, "relevance_delta_lower": -0.04924415118944936}
2026-08-06 21:05:36,387 | INFO | portfolio_selected | {"action": "repair_selected", "base_feasible": false, "cost": 0.05, "fatigue_upper": 0.0, "feasible": true, "lower_improvement": 0.2985139280765191, "mode": "repair", "provider_disparity_upper": 0.22587191358024694, "reason": "Base policy violates robust constraints; selected the best feasible repair by maximin improvement.", "relevance_delta_lower": -0.04413677084635825, "selected_interventions": ["repeat_cap"], "selected_mask": 1, "status": "repair_selected", "upper_improvement": 0.3130691025188375}
2026-08-06 21:05:36,388 | INFO | explanation_card_written | {"selected_mask": 1, "status": "repair_selected"}
2026-08-06 21:05:36,389 | INFO | robust_planning_completed | {"duration_seconds": 0.012677582999458537}
2026-08-06 21:05:36,389 | INFO | reporting_started | {}
2026-08-06 21:05:36,779 | INFO | assets_generated | {"figures": ["figures/figure_01_framework.png", "figures/figure_02_shapley_regions.png", "figures/figure_03_uncertainty_widths.png", "figures/figure_04_interaction_heatmap.png", "figures/figure_05_trajectory_comparison.png", "figures/figure_06_decision_card.png", "figures/figure_07_runtime_by_cardinality.png", "figures/figure_08_scenario_sensitivity.png"], "tables": ["tables/table_01_asset_registry.csv", "tables/table_02_benchmark_configuration.csv", "tables/table_03_attribution_regions.csv", "tables/table_04_uncertainty_summary.csv", "tables/table_05_portfolio_decision.csv", "tables/table_06_long_term_tradeoffs.csv", "tables/table_07_selection_comparison.csv", "tables/table_08_runtime_summary.csv"]}
2026-08-06 21:05:36,779 | INFO | reporting_completed | {"duration_seconds": 0.390666292001697}
2026-08-06 21:05:36,780 | INFO | run_finished | {"run_dir": "/Users/mlouhichi/Desktop/CURE-Rec/next-paper/paper-ideas/CURE-Rec/code/runs/calibration-lhs-20260806T195446Z/baseline/seed-sweep-20260806T195446Z/runs/calibration-baseline-seed-42-20260806T195446Z-a7ee83c5", "status": "completed"}
2026-08-06 21:05:36,782 | INFO | run_started | {"config_hash": "aa3c9a18a4daa98a", "run_id": "calibration-baseline-seed-43-20260806T200536Z-b530d05f"}
2026-08-06 21:05:36,783 | INFO | exact_game_started | {}
2026-08-06 21:05:36,783 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "nominal"}
2026-08-06 21:39:37,514 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.1346891128191804, "scenario": "nominal", "shapley_efficiency_gap": 2.7755575615628914e-17}
2026-08-06 21:39:37,515 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "fatigue_stress"}
2026-08-06 22:29:52,790 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.1335584679676869, "scenario": "fatigue_stress", "shapley_efficiency_gap": 5.551115123125783e-17}
2026-08-06 22:29:52,791 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "popularity_stress"}
2026-08-06 22:32:33,579 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.14862095677554493, "scenario": "popularity_stress", "shapley_efficiency_gap": 5.551115123125783e-17}
2026-08-06 22:32:33,580 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "mixed_stress"}
2026-08-06 22:35:14,571 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13703584273206604, "scenario": "mixed_stress", "shapley_efficiency_gap": -8.326672684688674e-17}
2026-08-06 22:35:14,577 | INFO | exact_game_completed | {"duration_seconds": 679.3377154169975}
2026-08-06 22:35:14,578 | INFO | robust_planning_started | {}
2026-08-06 22:35:14,578 | INFO | planner_mode_resolved | {"base_feasible": true, "base_lower_improvement": 0.0, "cost": 0.0, "fatigue_upper": 0.49475993375461946, "mode": "improvement", "provider_disparity_upper": 0.2593595679012346, "relevance_delta_lower": 0.0}
2026-08-06 22:35:14,579 | INFO | portfolio_rejected | {"active_interventions": ["novel_slot"], "coalition_mask": 16, "cost": 0.08, "fatigue_upper": 0.46216015017533696, "lower_improvement": -0.08255661441581219, "mode": "improvement", "provider_disparity_upper": 0.3324614197530864, "relevance_delta_lower": -0.04285973932971732}
2026-08-06 22:35:14,579 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "novel_slot"], "coalition_mask": 18, "cost": 0.18, "fatigue_upper": 0.4216473604586979, "lower_improvement": -0.148772858615079, "mode": "improvement", "provider_disparity_upper": 0.3247299382716049, "relevance_delta_lower": -0.042350964287570236}
2026-08-06 22:35:14,580 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "novel_slot"], "coalition_mask": 20, "cost": 0.16, "fatigue_upper": 0.42207852978502436, "lower_improvement": -0.1263693451151451, "mode": "improvement", "provider_disparity_upper": 0.3299305555555556, "relevance_delta_lower": -0.04335294164707992}
2026-08-06 22:35:14,580 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot"], "coalition_mask": 22, "cost": 0.26, "fatigue_upper": 0.41523959997490867, "lower_improvement": -0.224329333497243, "mode": "improvement", "provider_disparity_upper": 0.29210648148148155, "relevance_delta_lower": -0.03906307098448425}
2026-08-06 22:35:14,581 | INFO | portfolio_rejected | {"active_interventions": ["diversify", "novel_slot"], "coalition_mask": 24, "cost": 0.14, "fatigue_upper": 0.46413975686269127, "lower_improvement": -0.1389747035186309, "mode": "improvement", "provider_disparity_upper": 0.3208796296296297, "relevance_delta_lower": -0.03805139211273001}
2026-08-06 22:35:14,581 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot"], "coalition_mask": 26, "cost": 0.24, "fatigue_upper": 0.43158577172272367, "lower_improvement": -0.21429674952957756, "mode": "improvement", "provider_disparity_upper": 0.30644290123456797, "relevance_delta_lower": -0.04189632465464377}
2026-08-06 22:35:14,581 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify", "novel_slot"], "coalition_mask": 28, "cost": 0.22, "fatigue_upper": 0.43502048062785875, "lower_improvement": -0.1966465280516234, "mode": "improvement", "provider_disparity_upper": 0.3282253086419753, "relevance_delta_lower": -0.04468232504154712}
2026-08-06 22:35:14,582 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 30, "cost": 0.32, "fatigue_upper": 0.4283727710891955, "lower_improvement": -0.2913128701030419, "mode": "improvement", "provider_disparity_upper": 0.3070138888888889, "relevance_delta_lower": -0.03724351073383336}
2026-08-06 22:35:14,582 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 31, "cost": 0.37, "fatigue_upper": 0.0, "lower_improvement": -0.031222916099329534, "mode": "improvement", "provider_disparity_upper": 0.19977623456790128, "relevance_delta_lower": -0.03624147738146899}
2026-08-06 22:35:14,582 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 46, "cost": 0.36, "fatigue_upper": 0.43705830202489526, "lower_improvement": -0.3132476513543715, "mode": "improvement", "provider_disparity_upper": 0.08502314814814804, "relevance_delta_lower": -0.005619892013912331}
2026-08-06 22:35:14,583 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 47, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.06011106728370391, "mode": "improvement", "provider_disparity_upper": 0.10374228395061724, "relevance_delta_lower": -0.02999499734516553}
2026-08-06 22:35:14,583 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 54, "cost": 0.38, "fatigue_upper": 0.4387270232977046, "lower_improvement": -0.3431320893723503, "mode": "improvement", "provider_disparity_upper": 0.10621141975308634, "relevance_delta_lower": -0.017420094352256554}
2026-08-06 22:35:14,583 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 55, "cost": 0.43, "fatigue_upper": 0.0, "lower_improvement": -0.08856583119280781, "mode": "improvement", "provider_disparity_upper": 0.10935185185185192, "relevance_delta_lower": -0.03407593119006147}
2026-08-06 22:35:14,584 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 58, "cost": 0.36, "fatigue_upper": 0.43721548162611507, "lower_improvement": -0.3212449182808676, "mode": "improvement", "provider_disparity_upper": 0.09156635802469126, "relevance_delta_lower": -0.02398397980702016}

,point_id,varied_parameter,varied_value,is_baseline,seed_count,selected_portfolio_mode,selected_portfolio_mode_frequency,selection_stability,repeat_cap_selection_rate,base_feasibility_rate,...,fatigue_upper_mean,config_hash,recovered_seed_count,parameter_fatigue_strength,parameter_repeat_threshold,parameter_horizon,parameter_provider_threshold,parameter_provider_balance_strength,parameter_novelty_delayed_benefit,parameter_exploration_cost
0,baseline,baseline,None,True,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,1aada97a740787be,5,1.000000,3,12,0.280000,0.350000,0.000000,0.100000
1,lhs-001,joint_lhs,None,False,5,"('repeat_cap', 'tail_slot')",5,1.0,1.0,0.0,...,0.637762,069297af278b50e1,5,1.076705,1,17,0.324179,0.468345,0.060859,0.160875
2,lhs-002,joint_lhs,None,False,5,"('repeat_cap',)",4,0.8,1.0,0.2,...,0.226724,93eccbe1c389e91d,5,1.367944,2,10,0.262036,0.386883,0.070208,0.064656
3,lhs-003,joint_lhs,None,False,5,"('repeat_cap', 'explore_slot')",4,0.8,1.0,0.2,...,0.455595,768e4245a7319c24,5,1.047772,1,10,0.252429,0.327820,0.058298,0.025139
4,lhs-004,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.0,...,0.000000,ac4261f4e750d1db,5,0.761171,5,17,0.277819,0.423906,0.011495,0.079573
5,lhs-005,joint_lhs,None,False,5,"('repeat_cap',)",4,0.8,1.0,0.2,...,0.000000,d7fa97922454eaf5,5,1.129346,3,9,0.267317,0.297299,0.031857,0.067052
6,lhs-006,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,1.0,...,0.244154,bc4f57cc3729dcd6,5,0.870287,2,11,0.340421,0.795592,0.005958,0.037446
7,lhs-007,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,1.0,...,0.000000,4c0afd79d7336391,5,1.242046,5,8,0.348143,0.737506,0.007593,0.100119
8,lhs-008,joint_lhs,None,False,5,(),3,0.6,0.4,0.6,...,0.050975,69fd374f5f7be583,5,1.184850,4,6,0.257343,0.020907,0.077012,0.033885
9,lhs-009,joint_lhs,None,False,5,"('repeat_cap', 'tail_slot')",2,0.4,1.0,0.0,...,0.000000,b9dedc54492fc8e2,5,1.094094,3,11,0.213379,0.348619,0.018867,0.188931
10,lhs-010,joint_lhs,None,False,5,"('repeat_cap', 'tail_slot')",3,0.6,1.0,0.0,...,0.287209,cb4d90a70c6ccae5,5,0.896780,2,15,0.202175,0.526926,0.022262,0.133459
11,lhs-011,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.8,...,0.188627,d72bf018716e8a8d,5,1.335400,2,8,0.306200,0.188267,0.015231,0.080617
12,lhs-012,joint_lhs,None,False,5,"('provider_balance',)",3,0.6,0.0,0.2,...,0.000000,b0d5895a30d60e97,5,1.389977,5,4,0.224624,0.613251,0.039028,0.171015
13,lhs-013,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,1.0,...,0.000000,fc788fa65888e154,5,1.299739,4,12,0.356102,0.212581,0.000656,0.043142
14,lhs-014,joint_lhs,None,False,5,"('provider_balance',)",3,0.6,0.4,0.0,...,0.020164,820e32b08314c775,5,0.717610,4,5,0.208167,0.445507,0.044911,0.141594
15,lhs-015,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,1.0,...,0.000000,43ff047c3c3bf882,5,0.844032,3,7,0.317456,0.071381,0.029057,0.125841
16,lhs-016,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.0,...,0.330680,b92e2f7db8e27784,5,0.791926,2,18,0.242327,0.114874,0.076250,0.164750
17,lhs-017,joint_lhs,None,False,5,"('repeat_cap',)",4,0.8,1.0,0.0,...,0.000000,363045b71931d884,5,1.147642,3,14,0.228174,0.708471,0.055338,0.093025
18,lhs-018,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.0,...,0.000000,efc82039204d4da5,5,0.910602,3,20,0.233833,0.160694,0.068713,0.109682
19,lhs-019,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,1.0,...,0.355122,1583c7d9e9df3081,5,0.944533,1,6,0.333537,0.054797,0.024293,0.124512
20,lhs-020,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.4,...,0.000000,d11bdd166b125838,5,0.730055,3,14,0.299103,0.695154,0.036629,0.195665
21,lhs-021,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,fb180b03f3d8afc9,5,1.013425,4,19,0.308360,0.550152,0.042027,0.052567
22,lhs-022,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.0,...,0.311333,5797c8f16a924985,5,1.260827,2,16,0.330398,0.253552,0.051854,0.178880
23,lhs-023,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,ff453f13283a986d,5,0.990167,4,16,0.285965,0.577442,0.049087,0.154964
24,lhs-024,joint_lhs,None,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,2c636c3a6162791f,5,1.217157,4,13,0.288333,0.638761,0.064386,0.112749

## 6. Action 4 — inspect a completed calibration run

Paste the run directory printed by Action 2 or 3. This operation is cheap and never re-runs coalitions.

In [9]:
CALIBRATION_OUTPUT = (
    RUN_ROOT / "calibration-oat-20260805T184133Z"
)
if CALIBRATION_OUTPUT is not None:
    CALIBRATION_OUTPUT = Path(CALIBRATION_OUTPUT)
    calibration_summary = pd.read_csv(CALIBRATION_OUTPUT / 'calibration_summary.csv')
    calibration_configurations = pd.read_csv(CALIBRATION_OUTPUT / 'calibration_configurations.csv')
    calibration_manifest = json.loads((CALIBRATION_OUTPUT / 'calibration_manifest.json').read_text())
    display(calibration_summary)
    display(calibration_configurations)
    print(json.dumps({
        'design': calibration_manifest['design'],
        'seeds': calibration_manifest['seeds'],
        'base_config_hash': calibration_manifest['base_config_hash'],
        'figures': sorted(path.name for path in (CALIBRATION_OUTPUT / 'figures').glob('*.png')),
    }, indent=2))
else:
    print('Set CALIBRATION_OUTPUT after a calibration run to inspect its artifacts.')

,point_id,varied_parameter,varied_value,is_baseline,seed_count,selected_portfolio_mode,selected_portfolio_mode_frequency,selection_stability,repeat_cap_selection_rate,base_feasibility_rate,...,fatigue_upper_mean,config_hash,recovered_seed_count,parameter_fatigue_strength,parameter_repeat_threshold,parameter_horizon,parameter_provider_threshold,parameter_provider_balance_strength,parameter_novelty_delayed_benefit,parameter_exploration_cost
0,baseline,baseline,NaN,True,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,9798e91ec7ada5f2,5,1.00,3,12,0.28,0.35,0.00,0.10
1,oat-fatigue_strength-0p7500,fatigue_strength,0.75,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,aad136c8858c57bf,5,0.75,3,12,0.28,0.35,0.00,0.10
2,oat-fatigue_strength-1p2500,fatigue_strength,1.25,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,23b22ca44e5e1491,5,1.25,3,12,0.28,0.35,0.00,0.10
3,oat-repeat_threshold-2,repeat_threshold,2.00,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.262137,0e8c4922cb348567,5,1.00,2,12,0.28,0.35,0.00,0.10
4,oat-repeat_threshold-4,repeat_threshold,4.00,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,409a3894e128ae19,5,1.00,4,12,0.28,0.35,0.00,0.10
5,oat-horizon-8,horizon,8.00,False,5,"('repeat_cap',)",5,1.0,1.0,0.6,...,0.000000,3dfc6af2b625c550,5,1.00,3,8,0.28,0.35,0.00,0.10
6,oat-horizon-16,horizon,16.00,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,cdfbd1be96de4893,5,1.00,3,16,0.28,0.35,0.00,0.10
7,oat-provider_threshold-0p2400,provider_threshold,0.24,False,5,"('repeat_cap',)",4,0.8,1.0,0.0,...,0.000000,7796d9c704e67468,5,1.00,3,12,0.24,0.35,0.00,0.10
8,oat-provider_threshold-0p3200,provider_threshold,0.32,False,5,"('repeat_cap',)",5,1.0,1.0,0.6,...,0.000000,7b1e304238e1cae7,5,1.00,3,12,0.32,0.35,0.00,0.10
9,oat-provider_balance_strength-0p1500,provider_balance_strength,0.15,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,658db72cd92964cf,5,1.00,3,12,0.28,0.15,0.00,0.10
10,oat-provider_balance_strength-0p5500,provider_balance_strength,0.55,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,21c3770675721213,5,1.00,3,12,0.28,0.55,0.00,0.10
11,oat-novelty_delayed_benefit-0p0300,novelty_delayed_benefit,0.03,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,a3c275a65d844cc7,5,1.00,3,12,0.28,0.35,0.03,0.10
12,oat-novelty_delayed_benefit-0p0600,novelty_delayed_benefit,0.06,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,4c4f5115137005f7,5,1.00,3,12,0.28,0.35,0.06,0.10
13,oat-exploration_cost-0p0500,exploration_cost,0.05,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,acdbadfb6d3ff042,5,1.00,3,12,0.28,0.35,0.00,0.05
14,oat-exploration_cost-0p1500,exploration_cost,0.15,False,5,"('repeat_cap',)",5,1.0,1.0,0.2,...,0.000000,9d20c8c4af21855f,5,1.00,3,12,0.28,0.35,0.00,0.15

,point_id,varied_parameter,varied_value,is_baseline,config_hash,sweep_run_dir,recovered_seed_count,parameter_fatigue_strength,parameter_repeat_threshold,parameter_horizon,parameter_provider_threshold,parameter_provider_balance_strength,parameter_novelty_delayed_benefit,parameter_exploration_cost
0,baseline,baseline,NaN,True,9798e91ec7ada5f2,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.28,0.35,0.00,0.10
1,oat-fatigue_strength-0p7500,fatigue_strength,0.75,False,aad136c8858c57bf,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,0.75,3,12,0.28,0.35,0.00,0.10
2,oat-fatigue_strength-1p2500,fatigue_strength,1.25,False,23b22ca44e5e1491,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.25,3,12,0.28,0.35,0.00,0.10
3,oat-repeat_threshold-2,repeat_threshold,2.00,False,0e8c4922cb348567,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,2,12,0.28,0.35,0.00,0.10
4,oat-repeat_threshold-4,repeat_threshold,4.00,False,409a3894e128ae19,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,4,12,0.28,0.35,0.00,0.10
5,oat-horizon-8,horizon,8.00,False,3dfc6af2b625c550,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,8,0.28,0.35,0.00,0.10
6,oat-horizon-16,horizon,16.00,False,cdfbd1be96de4893,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,16,0.28,0.35,0.00,0.10
7,oat-provider_threshold-0p2400,provider_threshold,0.24,False,7796d9c704e67468,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.24,0.35,0.00,0.10
8,oat-provider_threshold-0p3200,provider_threshold,0.32,False,7b1e304238e1cae7,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.32,0.35,0.00,0.10
9,oat-provider_balance_strength-0p1500,provider_balance_strength,0.15,False,658db72cd92964cf,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.28,0.15,0.00,0.10
10,oat-provider_balance_strength-0p5500,provider_balance_strength,0.55,False,21c3770675721213,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.28,0.55,0.00,0.10
11,oat-novelty_delayed_benefit-0p0300,novelty_delayed_benefit,0.03,False,a3c275a65d844cc7,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.28,0.35,0.03,0.10
12,oat-novelty_delayed_benefit-0p0600,novelty_delayed_benefit,0.06,False,4c4f5115137005f7,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.28,0.35,0.06,0.10
13,oat-exploration_cost-0p0500,exploration_cost,0.05,False,acdbadfb6d3ff042,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.28,0.35,0.00,0.05
14,oat-exploration_cost-0p1500,exploration_cost,0.15,False,9d20c8c4af21855f,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...,5,1.00,3,12,0.28,0.35,0.00,0.15

{
  "design": "oat",
  "seeds": [
    42,
    43,
    44,
    45,
    46
  ],
  "base_config_hash": "41b09c43d0bc6c0e",
  "figures": [
    "calibration_figure_decision_stability.png",
    "calibration_figure_oat_lower_improvement.png",
    "calibration_figure_repeat_cap_shapley.png"
  ]
}

## Interpretation gate

Report this study as sensitivity of the disclosed CURE-Sim behavioral model. A stable `repeat_cap` selection rate across these settings supports simulator robustness; it does **not** turn MovieLens ratings into logged causal policy evidence. Retain configurations with unfavorable results, feasibility failures, and repair decisions.