# CURE-Rec — remaining review closure

This notebook is the single control surface for the remaining review items. It never edits the registered YAML configuration. Run all cells from top to bottom. Actions that require unavailable data or a new policy implementation are recorded as explicit skips; no result is fabricated.

In [1]:
from pathlib import Path
import sys,json,re,time
import pandas as pd

C=[Path.cwd(),Path.cwd()/'paper-ideas'/'CURE-Rec'/'code',*Path.cwd().parents]
ROOT=next(p for p in C if (p/'pyproject.toml').exists() and (p/'cure_rec').exists())
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from cure_rec.config import load_settings
from cure_rec.pipeline import run_experiment
from cure_rec.revision_suite import objective_ablation, paired_user_statistics

CONFIG=ROOT/'configs'/'curesim_full.yaml'
RESULTS=ROOT/'results'/'reviewer_phase_assets'
PAPER=ROOT.parent/'paper'/'cure-rec-springer'/'cure-rec.tex'
RUN_ALL=True
RUN_DIVERGENT_SELECTOR=True
RUN_UTILITY_SENSITIVITY=True
RUN_CONSTRAINT_FRONTIER=True
RUN_SEMI_REAL=False  # requires a declared replay/world-model protocol
RUN_INTEGRATED_SCALING=False  # requires actual 8/10 policy operators
print('Root:',ROOT)

Root: /Users/mlouhichi/Desktop/CURE-Rec/next-paper/paper-ideas/CURE-Rec/code

## 1. Manuscript consistency audit

In [2]:
text=PAPER.read_text()
checks={
 'free_F4_user_index': bool(re.search(r'Q_\{j,t\+1\}.*1\{j\\in L_\{u,t\}\}',text)),
 'old_decision_faithful': 'decision-faithful attribution' in text,
 'old_preregistered': 'preregistered' in text,
 'old_reviewer_language': 'reviewer-revision checks' in text or 'Reviewer-revision evidence' in text,
 'table_3_reference': 'Table 3' in text,
 'artifact_section': 'Artifact inventory' in text,
 'cost_definition': 'c(S)=\\sum' in text,
 'gini_definition': 'G(x)=' in text,
}
print(json.dumps(checks,indent=2))
if checks['old_decision_faithful'] or checks['old_preregistered'] or checks['old_reviewer_language'] or checks['free_F4_user_index']:
    print('Manuscript still has terminology/notation items requiring manual editing.')

{
  "free_F4_user_index": false,
  "old_decision_faithful": false,
  "old_preregistered": false,
  "old_reviewer_language": true,
  "table_3_reference": false,
  "artifact_section": true,
  "cost_definition": false,
  "gini_definition": true
}
Manuscript still has terminology/notation items requiring manual editing.

## 2. Utility-weight sensitivity

Runs predeclared alternative utility vectors on one exact full game each. Results are sensitivity evidence, not performance gains.

In [3]:
WEIGHTS=[
 {'name':'satisfaction_heavy','satisfaction_weight':0.85,'retention_weight':0.15,'fatigue_weight':0.35,'cost_weight':1.0},
 {'name':'retention_heavy','satisfaction_weight':0.35,'retention_weight':0.65,'fatigue_weight':0.35,'cost_weight':1.0},
 {'name':'fatigue_averse','satisfaction_weight':0.70,'retention_weight':0.30,'fatigue_weight':0.70,'cost_weight':1.0},
 {'name':'cost_averse','satisfaction_weight':0.70,'retention_weight':0.30,'fatigue_weight':0.35,'cost_weight':2.0},
]
if RUN_ALL and RUN_UTILITY_SENSITIVITY:
 rows=[]
 for w in WEIGHTS:
  cfg=load_settings(CONFIG); cfg.run.name='utility-'+w['name']; cfg.run.output_root=ROOT/'runs'/'reviewer-closure';
  for k,v in w.items():
   if k!='name': setattr(cfg.utility,k,v)
  logger,game,decision=run_experiment(cfg)
  rows.append({'setting':w['name'],'portfolio':';'.join(decision.selected_interventions),'status':decision.status.value,'mode':decision.mode.value,'lower_improvement':decision.lower_improvement,'base_feasible':decision.base_feasible,'source_run':str(logger.run_dir)})
 utility=pd.DataFrame(rows); out=RESULTS/'reviewer_closure'; out.mkdir(parents=True,exist_ok=True); utility.to_csv(out/'utility_weight_sensitivity.csv',index=False); display(utility)
else: print('Utility sensitivity skipped.')

2026-08-18 01:38:28,496 | INFO | run_started | {"config_hash": "787db96ce0a1ccb0", "run_id": "utility-satisfaction_heavy-20260818T003828Z-ec4ecb31"}
2026-08-18 01:38:28,497 | INFO | exact_game_started | {}
2026-08-18 01:38:28,498 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "nominal"}
2026-08-18 01:41:06,288 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.1739479533216729, "scenario": "nominal", "shapley_efficiency_gap": -2.7755575615628914e-17}
2026-08-18 01:41:06,289 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "fatigue_stress"}
2026-08-18 01:43:48,445 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.17480596369523932, "scenario": "fatigue_stress", "shapley_efficiency_gap": -5.551115123125783e-17}
2026-08-18 01:43:48,446 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "popularity_stress"}
2026-08-18 01:46:26,480 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.18800418676289987, "scenario": "popularity_stress", "shapley_efficiency_gap": 0.0}
2026-08-18 01:46:26,482 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "mixed_stress"}
2026-08-18 01:49:04,421 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.18251162509597774, "scenario": "mixed_stress", "shapley_efficiency_gap": 0.0}
2026-08-18 01:49:04,427 | INFO | robust_game_completed | {"robust_grand_improvement": -0.18800418676289987, "robust_shapley_efficiency_gap": 1.3877787807814457e-16}
2026-08-18 01:49:04,431 | INFO | exact_game_completed | {"duration_seconds": 635.9688969999552}
2026-08-18 01:49:04,432 | INFO | robust_planning_started | {}
2026-08-18 01:49:04,432 | INFO | planner_mode_resolved | {"base_feasible": false, "base_lower_improvement": 0.0, "cost": 0.0, "fatigue_upper": 0.49824230098806155, "mode": "repair", "provider_disparity_upper": 0.3151543209876544, "relevance_delta_lower": 0.0}
2026-08-18 01:49:04,433 | INFO | portfolio_rejected | {"active_interventions": [], "coalition_mask": 0, "cost": 0.0, "fatigue_upper": 0.49824230098806155, "lower_improvement": 0.0, "mode": "repair", "provider_disparity_upper": 0.3151543209876544, "relevance_delta_lower": 0.0}
2026-08-18 01:49:04,433 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot"], "coalition_mask": 2, "cost": 0.1, "fatigue_upper": 0.46305694500486366, "lower_improvement": -0.07581990030959573, "mode": "repair", "provider_disparity_upper": 0.29288580246913587, "relevance_delta_lower": -0.007039870883891575}
2026-08-18 01:49:04,434 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot"], "coalition_mask": 4, "cost": 0.08, "fatigue_upper": 0.4648932204786902, "lower_improvement": -0.054438676667238395, "mode": "repair", "provider_disparity_upper": 0.28178240740740734, "relevance_delta_lower": -0.004837434258011197}
2026-08-18 01:49:04,434 | INFO | portfolio_rejected | {"active_interventions": ["diversify"], "coalition_mask": 8, "cost": 0.06, "fatigue_upper": 0.4934736740096391, "lower_improvement": -0.05894547235791764, "mode": "repair", "provider_disparity_upper": 0.31770833333333326, "relevance_delta_lower": -6.745981224032249e-05}
2026-08-18 01:49:04,434 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify"], "coalition_mask": 10, "cost": 0.16, "fatigue_upper": 0.4665261551940821, "lower_improvement": -0.14151840751061037, "mode": "repair", "provider_disparity_upper": 0.3073842592592593, "relevance_delta_lower": -0.0060451505641295755}
2026-08-18 01:49:04,435 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify"], "coalition_mask": 12, "cost": 0.14, "fatigue_upper": 0.4715309883795782, "lower_improvement": -0.12144718725294545, "mode": "repair", "provider_disparity_upper": 0.3113734567901234, "relevance_delta_lower": -0.0029919432763102494}
2026-08-18 01:49:04,435 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify"], "coalition_mask": 14, "cost": 0.24, "fatigue_upper": 0.43359548337015746, "lower_improvement": -0.19599914460577667, "mode": "repair", "provider_disparity_upper": 0.28331018518518514, "relevance_delta_lower": -0.010304694831896}
2026-08-18 01:49:04,435 | INFO | portfolio_rejected | {"active_interventions": ["novel_slot"], "coalition_mask": 16, "cost": 0.08, "fatigue_upper": 0.46812137445644175, "lower_improvement": -0.08568484286784578, "mode": "repair", "provider_disparity_upper": 0.38573302469135795, "relevance_delta_lower": -0.03918691196597257}
2026-08-18 01:49:04,436 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "novel_slot"], "coalition_mask": 18, "cost": 0.18, "fatigue_upper": 0.4286087752910208, "lower_improvement": -0.15664072370680288, "mode": "repair", "provider_disparity_upper": 0.3775077160493827, "relevance_delta_lower": -0.04588572116305478}
2026-08-18 01:49:04,436 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "novel_slot"], "coalition_mask": 20, "cost": 0.16, "fatigue_upper": 0.4288520181700854, "lower_improvement": -0.1347376261223214, "mode": "repair", "provider_disparity_upper": 0.37043209876543215, "relevance_delta_lower": -0.04545495874023986}
2026-08-18 01:49:04,437 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot"], "coalition_mask": 22, "cost": 0.26, "fatigue_upper": 0.4203030694539533, "lower_improvement": -0.225990231995294, "mode": "repair", "provider_disparity_upper": 0.3650925925925925, "relevance_delta_lower": -0.03275402342635392}
2026-08-18 01:49:04,437 | INFO | portfolio_rejected | {"active_interventions": ["diversify", "novel_slot"], "coalition_mask": 24, "cost": 0.14, "fatigue_upper": 0.47136837922486796, "lower_improvement": -0.13800524155660654, "mode": "repair", "provider_disparity_upper": 0.3703395061728394, "relevance_delta_lower": -0.028498674155469805}
2026-08-18 01:49:04,437 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot"], "coalition_mask": 26, "cost": 0.24, "fatigue_upper": 0.4367115494878448, "lower_improvement": -0.2145657028043606, "mode": "repair", "provider_disparity_upper": 0.3700848765432099, "relevance_delta_lower": -0.03528217326141503}
2026-08-18 01:49:04,438 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify", "novel_slot"], "coalition_mask": 28, "cost": 0.22, "fatigue_upper": 0.4385750801734416, "lower_improvement": -0.20053768218362014, "mode": "repair", "provider_disparity_upper": 0.37462962962962965, "relevance_delta_lower": -0.038154427494082044}
2026-08-18 01:49:04,438 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 30, "cost": 0.32, "fatigue_upper": 0.43335577977960904, "lower_improvement": -0.2942955075868013, "mode": "repair", "provider_disparity_upper": 0.36135030864197537, "relevance_delta_lower": -0.028504237887276296}
2026-08-18 01:49:04,438 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 31, "cost": 0.37, "fatigue_upper": 0.0, "lower_improvement": -0.06951421588333206, "mode": "repair", "provider_disparity_upper": 0.24209876543209874, "relevance_delta_lower": -0.044980691988371624}
2026-08-18 01:49:04,439 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 46, "cost": 0.36, "fatigue_upper": 0.43960972420257644, "lower_improvement": -0.31926531304711303, "mode": "repair", "provider_disparity_upper": 0.08564814814814814, "relevance_delta_lower": -0.009307748023261175}
2026-08-18 01:49:04,439 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 47, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.09883645215599957, "mode": "repair", "provider_disparity_upper": 0.12369598765432088, "relevance_delta_lower": -0.040636445358968154}
2026-08-18 01:49:04,439 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 54, "cost": 0.38, "fatigue_upper": 0.44451496814785885, "lower_improvement": -0.35136057720268277, "mode": "repair", "provider_disparity_upper": 0.1183101851851851, "relevance_delta_lower": -0.015074180616582944}
2026-08-18 01:49:04,440 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 55, "cost": 0.43, "fatigue_upper": 0.0, "lower_improvement": -0.1300778795187783, "mode": "repair", "provider_disparity_upper": 0.1216049382716049, "relevance_delta_lower": -0.046314952536664844}
2026-08-18 01:49:04,440 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 58, "cost": 0.36, "fatigue_upper": 0.43790742449355374, "lower_improvement": -0.32759345543969515, "mode": "repair", "provider_disparity_upper": 0.09783179012345666, "relevance_delta_lower": -0.02257069381127974}
2026-08-18 01:49:04,440 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 59, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.1092510057481696, "mode": "repair", "provider_disparity_upper": 0.11020833333333324, "relevance_delta_lower": -0.046721314901966626}
2026-08-18 01:49:04,441 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 61, "cost": 0.39, "fatigue_upper": 0.0, "lower_improvement": -0.09140246619211567, "mode": "repair", "provider_disparity_upper": 0.12075617283950613, "relevance_delta_lower": -0.04453998042091023}
2026-08-18 01:49:04,441 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 62, "cost": 0.44, "fatigue_upper": 0.44378770693723096, "lower_improvement": -0.40940227179355854, "mode": "repair", "provider_disparity_upper": 0.09979938271604927, "relevance_delta_lower": -0.01670951684908817}
2026-08-18 01:49:04,441 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 63, "cost": 0.49, "fatigue_upper": 0.0, "lower_improvement": -0.18800418676289987, "mode": "repair", "provider_disparity_upper": 0.11733024691358018, "relevance_delta_lower": -0.04420629494664963}
2026-08-18 01:49:04,442 | INFO | portfolio_selected | {"action": "repair_selected", "base_feasible": false, "cost": 0.05, "fatigue_upper": 0.0, "feasible": true, "lower_improvement": 0.25705766941060104, "mode": "repair", "provider_disparity_upper": 0.2442746913580247, "reason": "Base policy violates robust constraints; selected the best feasible repair by maximin improvement.", "relevance_delta_lower": -0.041477531911315535, "selected_interventions": ["repeat_cap"], "selected_mask": 1, "status": "repair_selected", "upper_improvement": 0.27307481958900093}
2026-08-18 01:49:04,444 | INFO | explanation_card_written | {"selected_mask": 1, "status": "repair_selected"}
2026-08-18 01:49:04,444 | INFO | robust_planning_completed | {"duration_seconds": 0.01258062501437962}
2026-08-18 01:49:04,445 | INFO | reporting_started | {}
2026-08-18 01:49:04,844 | INFO | assets_generated | {"figures": ["figures/figure_01_framework.png", "figures/figure_02_shapley_regions.png", "figures/figure_03_uncertainty_widths.png", "figures/figure_04_interaction_heatmap.png", "figures/figure_05_trajectory_comparison.png", "figures/figure_06_decision_card.png", "figures/figure_07_runtime_by_cardinality.png", "figures/figure_08_scenario_sensitivity.png"], "tables": ["tables/table_01_asset_registry.csv", "tables/table_02_benchmark_configuration.csv", "tables/table_03_attribution_regions.csv", "tables/table_04_uncertainty_summary.csv", "tables/table_05_portfolio_decision.csv", "tables/table_06_long_term_tradeoffs.csv", "tables/table_07_selection_comparison.csv", "tables/table_08_runtime_summary.csv"]}
2026-08-18 01:49:04,845 | INFO | reporting_completed | {"duration_seconds": 0.3999851249391213}
2026-08-18 01:49:04,845 | INFO | run_finished | {"run_dir": "/Users/mlouhichi/Desktop/CURE-Rec/next-paper/paper-ideas/CURE-Rec/code/runs/reviewer-closure/utility-satisfaction_heavy-20260818T003828Z-ec4ecb31", "status": "completed"}
2026-08-18 01:49:04,848 | INFO | run_started | {"config_hash": "acec9447875ab8c9", "run_id": "utility-retention_heavy-20260818T004904Z-f3fff175"}
2026-08-18 01:49:04,849 | INFO | exact_game_started | {}
2026-08-18 01:49:04,849 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "nominal"}
2026-08-18 01:51:42,231 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.03824918799607657, "scenario": "nominal", "shapley_efficiency_gap": 3.469446951953614e-17}
2026-08-18 01:51:42,232 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "fatigue_stress"}
2026-08-18 01:54:19,764 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.04360426864546635, "scenario": "fatigue_stress", "shapley_efficiency_gap": 5.551115123125783e-17}
2026-08-18 01:54:19,765 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "popularity_stress"}
2026-08-18 02:03:08,906 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.0602356033738346, "scenario": "popularity_stress", "shapley_efficiency_gap": -6.938893903907228e-18}
2026-08-18 02:03:08,908 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "mixed_stress"}
2026-08-18 02:05:49,445 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.05565997526182331, "scenario": "mixed_stress", "shapley_efficiency_gap": -2.7755575615628914e-17}
2026-08-18 02:05:49,450 | INFO | robust_game_completed | {"robust_grand_improvement": -0.0602356033738346, "robust_shapley_efficiency_gap": 3.469446951953614e-17}
2026-08-18 02:05:49,453 | INFO | exact_game_completed | {"duration_seconds": 636.1327730000485}
2026-08-18 02:05:49,454 | INFO | robust_planning_started | {}
2026-08-18 02:05:49,454 | INFO | planner_mode_resolved | {"base_feasible": false, "base_lower_improvement": 0.0, "cost": 0.0, "fatigue_upper": 0.49824230098806155, "mode": "repair", "provider_disparity_upper": 0.3151543209876544, "relevance_delta_lower": 0.0}
2026-08-18 02:05:49,455 | INFO | portfolio_rejected | {"active_interventions": [], "coalition_mask": 0, "cost": 0.0, "fatigue_upper": 0.49824230098806155, "lower_improvement": 0.0, "mode": "repair", "provider_disparity_upper": 0.3151543209876544, "relevance_delta_lower": 0.0}
2026-08-18 02:05:49,455 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot"], "coalition_mask": 2, "cost": 0.1, "fatigue_upper": 0.46305694500486366, "lower_improvement": -0.06101063993721023, "mode": "repair", "provider_disparity_upper": 0.29288580246913587, "relevance_delta_lower": -0.007039870883891575}
2026-08-18 02:05:49,456 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot"], "coalition_mask": 4, "cost": 0.08, "fatigue_upper": 0.4648932204786902, "lower_improvement": -0.04151911517793688, "mode": "repair", "provider_disparity_upper": 0.28178240740740734, "relevance_delta_lower": -0.004837434258011197}
2026-08-18 02:05:49,456 | INFO | portfolio_rejected | {"active_interventions": ["diversify"], "coalition_mask": 8, "cost": 0.06, "fatigue_upper": 0.4934736740096391, "lower_improvement": -0.058522816362982066, "mode": "repair", "provider_disparity_upper": 0.31770833333333326, "relevance_delta_lower": -6.745981224032249e-05}
2026-08-18 02:05:49,456 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify"], "coalition_mask": 10, "cost": 0.16, "fatigue_upper": 0.4665261551940821, "lower_improvement": -0.13097656474872282, "mode": "repair", "provider_disparity_upper": 0.3073842592592593, "relevance_delta_lower": -0.0060451505641295755}
2026-08-18 02:05:49,457 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify"], "coalition_mask": 12, "cost": 0.14, "fatigue_upper": 0.4715309883795782, "lower_improvement": -0.11023900970196376, "mode": "repair", "provider_disparity_upper": 0.3113734567901234, "relevance_delta_lower": -0.0029919432763102494}
2026-08-18 02:05:49,457 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify"], "coalition_mask": 14, "cost": 0.24, "fatigue_upper": 0.43359548337015746, "lower_improvement": -0.1709624123369204, "mode": "repair", "provider_disparity_upper": 0.28331018518518514, "relevance_delta_lower": -0.010304694831896}
2026-08-18 02:05:49,457 | INFO | portfolio_rejected | {"active_interventions": ["novel_slot"], "coalition_mask": 16, "cost": 0.08, "fatigue_upper": 0.46812137445644175, "lower_improvement": -0.06320800378295871, "mode": "repair", "provider_disparity_upper": 0.38573302469135795, "relevance_delta_lower": -0.03918691196597257}
2026-08-18 02:05:49,458 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "novel_slot"], "coalition_mask": 18, "cost": 0.18, "fatigue_upper": 0.4286087752910208, "lower_improvement": -0.11755157903703789, "mode": "repair", "provider_disparity_upper": 0.3775077160493827, "relevance_delta_lower": -0.04588572116305478}
2026-08-18 02:05:49,458 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "novel_slot"], "coalition_mask": 20, "cost": 0.16, "fatigue_upper": 0.4288520181700854, "lower_improvement": -0.09534613371837475, "mode": "repair", "provider_disparity_upper": 0.37043209876543215, "relevance_delta_lower": -0.04545495874023986}
2026-08-18 02:05:49,458 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot"], "coalition_mask": 22, "cost": 0.26, "fatigue_upper": 0.4203030694539533, "lower_improvement": -0.18495880741410708, "mode": "repair", "provider_disparity_upper": 0.3650925925925925, "relevance_delta_lower": -0.03275402342635392}
2026-08-18 02:05:49,458 | INFO | portfolio_rejected | {"active_interventions": ["diversify", "novel_slot"], "coalition_mask": 24, "cost": 0.14, "fatigue_upper": 0.47136837922486796, "lower_improvement": -0.11942005401412836, "mode": "repair", "provider_disparity_upper": 0.3703395061728394, "relevance_delta_lower": -0.028498674155469805}
2026-08-18 02:05:49,459 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot"], "coalition_mask": 26, "cost": 0.24, "fatigue_upper": 0.4367115494878448, "lower_improvement": -0.1824067540870733, "mode": "repair", "provider_disparity_upper": 0.3700848765432099, "relevance_delta_lower": -0.03528217326141503}
2026-08-18 02:05:49,459 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify", "novel_slot"], "coalition_mask": 28, "cost": 0.22, "fatigue_upper": 0.4385750801734416, "lower_improvement": -0.1690417591189708, "mode": "repair", "provider_disparity_upper": 0.37462962962962965, "relevance_delta_lower": -0.038154427494082044}
2026-08-18 02:05:49,459 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 30, "cost": 0.32, "fatigue_upper": 0.43335577977960904, "lower_improvement": -0.26337624400538023, "mode": "repair", "provider_disparity_upper": 0.36135030864197537, "relevance_delta_lower": -0.028504237887276296}

,setting,portfolio,status,mode,lower_improvement,base_feasible,source_run
0,satisfaction_heavy,repeat_cap,repair_selected,repair,0.257058,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...
1,retention_heavy,repeat_cap,repair_selected,repair,0.381849,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...
2,fatigue_averse,repeat_cap,repair_selected,repair,0.461201,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...
3,cost_averse,repeat_cap,repair_selected,repair,0.244495,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...

## 3. Constraint frontier

Runs a predeclared grid of budget, relevance, provider and fatigue thresholds.

In [4]:
FRONTIER=[
 {'name':'strict_provider','budget':0.35,'relevance':-0.08,'provider':0.24,'fatigue':0.65},
 {'name':'baseline','budget':0.35,'relevance':-0.08,'provider':0.28,'fatigue':0.65},
 {'name':'relaxed_provider','budget':0.35,'relevance':-0.08,'provider':0.34,'fatigue':0.65},
 {'name':'tight_budget','budget':0.20,'relevance':-0.08,'provider':0.28,'fatigue':0.65},
 {'name':'tight_relevance','budget':0.35,'relevance':-0.03,'provider':0.28,'fatigue':0.65},
 {'name':'tight_fatigue','budget':0.35,'relevance':-0.08,'provider':0.28,'fatigue':0.45},
]
if RUN_ALL and RUN_CONSTRAINT_FRONTIER:
 rows=[]
 for f in FRONTIER:
  cfg=load_settings(CONFIG); cfg.run.name='frontier-'+f['name']; cfg.run.output_root=ROOT/'runs'/'reviewer-closure'; cfg.constraints.budget=f['budget']; cfg.constraints.min_relevance_delta=f['relevance']; cfg.constraints.max_provider_disparity=f['provider']; cfg.constraints.max_fatigue=f['fatigue']
  logger,game,decision=run_experiment(cfg); rows.append({'setting':f['name'],**f,'portfolio':';'.join(decision.selected_interventions),'status':decision.status.value,'mode':decision.mode.value,'lower_improvement':decision.lower_improvement,'base_feasible':decision.base_feasible,'source_run':str(logger.run_dir)})
 frontier=pd.DataFrame(rows); out=RESULTS/'reviewer_closure'; out.mkdir(parents=True,exist_ok=True); frontier.to_csv(out/'constraint_frontier.csv',index=False); display(frontier)
else: print('Constraint frontier skipped.')

2026-08-18 02:41:49,933 | INFO | run_started | {"config_hash": "c194e15c8164b388", "run_id": "frontier-strict_provider-20260818T014149Z-0d8d0944"}
2026-08-18 02:41:49,934 | INFO | exact_game_started | {}
2026-08-18 02:41:49,935 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "nominal"}
2026-08-18 02:44:31,255 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13323832372399413, "scenario": "nominal", "shapley_efficiency_gap": 1.3877787807814457e-16}
2026-08-18 02:44:31,256 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "fatigue_stress"}
2026-08-18 02:47:13,002 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13544545518030754, "scenario": "fatigue_stress", "shapley_efficiency_gap": 0.0}
2026-08-18 02:47:13,003 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "popularity_stress"}
2026-08-18 02:49:52,591 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.14967361174618043, "scenario": "popularity_stress", "shapley_efficiency_gap": -2.7755575615628914e-17}
2026-08-18 02:49:52,591 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "mixed_stress"}
2026-08-18 02:54:16,570 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.14445613014573144, "scenario": "mixed_stress", "shapley_efficiency_gap": 0.0}
2026-08-18 02:54:16,574 | INFO | robust_game_completed | {"robust_grand_improvement": -0.14967361174618043, "robust_shapley_efficiency_gap": 0.0}
2026-08-18 02:54:16,578 | INFO | exact_game_completed | {"duration_seconds": 643.1985950829694}
2026-08-18 02:54:16,579 | INFO | robust_planning_started | {}
2026-08-18 02:54:16,579 | INFO | planner_mode_resolved | {"base_feasible": false, "base_lower_improvement": 0.0, "cost": 0.0, "fatigue_upper": 0.49824230098806155, "mode": "repair", "provider_disparity_upper": 0.3151543209876544, "relevance_delta_lower": 0.0}
2026-08-18 02:54:16,580 | INFO | portfolio_rejected | {"active_interventions": [], "coalition_mask": 0, "cost": 0.0, "fatigue_upper": 0.49824230098806155, "lower_improvement": 0.0, "mode": "repair", "provider_disparity_upper": 0.3151543209876544, "relevance_delta_lower": 0.0}
2026-08-18 02:54:16,580 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap"], "coalition_mask": 1, "cost": 0.05, "fatigue_upper": 0.0, "lower_improvement": 0.2944949756908204, "mode": "repair", "provider_disparity_upper": 0.2442746913580247, "relevance_delta_lower": -0.041477531911315535}
2026-08-18 02:54:16,581 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot"], "coalition_mask": 2, "cost": 0.1, "fatigue_upper": 0.46305694500486366, "lower_improvement": -0.07137712219788017, "mode": "repair", "provider_disparity_upper": 0.29288580246913587, "relevance_delta_lower": -0.007039870883891575}
2026-08-18 02:54:16,581 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot"], "coalition_mask": 4, "cost": 0.08, "fatigue_upper": 0.4648932204786902, "lower_improvement": -0.05056280822044795, "mode": "repair", "provider_disparity_upper": 0.28178240740740734, "relevance_delta_lower": -0.004837434258011197}
2026-08-18 02:54:16,582 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot"], "coalition_mask": 6, "cost": 0.18, "fatigue_upper": 0.41930163695972245, "lower_improvement": -0.11454815942689156, "mode": "repair", "provider_disparity_upper": 0.27435185185185174, "relevance_delta_lower": -0.013513391184058476}
2026-08-18 02:54:16,583 | INFO | portfolio_rejected | {"active_interventions": ["diversify"], "coalition_mask": 8, "cost": 0.06, "fatigue_upper": 0.4934736740096391, "lower_improvement": -0.05876389131453319, "mode": "repair", "provider_disparity_upper": 0.31770833333333326, "relevance_delta_lower": -6.745981224032249e-05}
2026-08-18 02:54:16,583 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify"], "coalition_mask": 10, "cost": 0.16, "fatigue_upper": 0.4665261551940821, "lower_improvement": -0.13825722665453052, "mode": "repair", "provider_disparity_upper": 0.3073842592592593, "relevance_delta_lower": -0.0060451505641295755}
2026-08-18 02:54:16,584 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify"], "coalition_mask": 12, "cost": 0.14, "fatigue_upper": 0.4715309883795782, "lower_improvement": -0.11798244648637923, "mode": "repair", "provider_disparity_upper": 0.3113734567901234, "relevance_delta_lower": -0.0029919432763102494}
2026-08-18 02:54:16,585 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify"], "coalition_mask": 14, "cost": 0.24, "fatigue_upper": 0.43359548337015746, "lower_improvement": -0.18848812492511985, "mode": "repair", "provider_disparity_upper": 0.28331018518518514, "relevance_delta_lower": -0.010304694831896}
2026-08-18 02:54:16,585 | INFO | portfolio_rejected | {"active_interventions": ["novel_slot"], "coalition_mask": 16, "cost": 0.08, "fatigue_upper": 0.46812137445644175, "lower_improvement": -0.0789417911423797, "mode": "repair", "provider_disparity_upper": 0.38573302469135795, "relevance_delta_lower": -0.03918691196597257}
2026-08-18 02:54:16,586 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "novel_slot"], "coalition_mask": 17, "cost": 0.13, "fatigue_upper": 0.0, "lower_improvement": 0.19978861528897585, "mode": "repair", "provider_disparity_upper": 0.26254629629629633, "relevance_delta_lower": -0.051779443652007706}
2026-08-18 02:54:16,586 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "novel_slot"], "coalition_mask": 18, "cost": 0.18, "fatigue_upper": 0.4286087752910208, "lower_improvement": -0.14491398030587338, "mode": "repair", "provider_disparity_upper": 0.3775077160493827, "relevance_delta_lower": -0.04588572116305478}
2026-08-18 02:54:16,587 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "novel_slot"], "coalition_mask": 19, "cost": 0.23, "fatigue_upper": 0.0, "lower_improvement": 0.1019132443172851, "mode": "repair", "provider_disparity_upper": 0.2524228395061727, "relevance_delta_lower": -0.05369019754348059}
2026-08-18 02:54:16,587 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "novel_slot"], "coalition_mask": 20, "cost": 0.16, "fatigue_upper": 0.4288520181700854, "lower_improvement": -0.12292017840113745, "mode": "repair", "provider_disparity_upper": 0.37043209876543215, "relevance_delta_lower": -0.04545495874023986}
2026-08-18 02:54:16,588 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot"], "coalition_mask": 22, "cost": 0.26, "fatigue_upper": 0.4203030694539533, "lower_improvement": -0.21368080462093797, "mode": "repair", "provider_disparity_upper": 0.3650925925925925, "relevance_delta_lower": -0.03275402342635392}
2026-08-18 02:54:16,588 | INFO | portfolio_rejected | {"active_interventions": ["diversify", "novel_slot"], "coalition_mask": 24, "cost": 0.14, "fatigue_upper": 0.47136837922486796, "lower_improvement": -0.13217026618788907, "mode": "repair", "provider_disparity_upper": 0.3703395061728394, "relevance_delta_lower": -0.028498674155469805}
2026-08-18 02:54:16,588 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "diversify", "novel_slot"], "coalition_mask": 25, "cost": 0.19, "fatigue_upper": 0.0, "lower_improvement": 0.14514882019124975, "mode": "repair", "provider_disparity_upper": 0.25999228395061724, "relevance_delta_lower": -0.045889621087857324}
2026-08-18 02:54:16,589 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot"], "coalition_mask": 26, "cost": 0.24, "fatigue_upper": 0.4367115494878448, "lower_improvement": -0.20491801818917443, "mode": "repair", "provider_disparity_upper": 0.3700848765432099, "relevance_delta_lower": -0.03528217326141503}
2026-08-18 02:54:16,589 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "diversify", "novel_slot"], "coalition_mask": 27, "cost": 0.29000000000000004, "fatigue_upper": 0.0, "lower_improvement": 0.04613237412748783, "mode": "repair", "provider_disparity_upper": 0.255787037037037, "relevance_delta_lower": -0.048270062711537554}
2026-08-18 02:54:16,589 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify", "novel_slot"], "coalition_mask": 28, "cost": 0.22, "fatigue_upper": 0.4385750801734416, "lower_improvement": -0.19108890526422542, "mode": "repair", "provider_disparity_upper": 0.37462962962962965, "relevance_delta_lower": -0.038154427494082044}
2026-08-18 02:54:16,590 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 30, "cost": 0.32, "fatigue_upper": 0.43335577977960904, "lower_improvement": -0.28501972851237506, "mode": "repair", "provider_disparity_upper": 0.36135030864197537, "relevance_delta_lower": -0.028504237887276296}
2026-08-18 02:54:16,591 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot"], "coalition_mask": 31, "cost": 0.37, "fatigue_upper": 0.0, "lower_improvement": -0.0309171651394774, "mode": "repair", "provider_disparity_upper": 0.24209876543209874, "relevance_delta_lower": -0.044980691988371624}
2026-08-18 02:54:16,591 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 46, "cost": 0.36, "fatigue_upper": 0.43960972420257644, "lower_improvement": -0.31255272976779847, "mode": "repair", "provider_disparity_upper": 0.08564814814814814, "relevance_delta_lower": -0.009307748023261175}
2026-08-18 02:54:16,592 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "provider_balance"], "coalition_mask": 47, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.06212371265814476, "mode": "repair", "provider_disparity_upper": 0.12369598765432088, "relevance_delta_lower": -0.040636445358968154}
2026-08-18 02:54:16,592 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 54, "cost": 0.38, "fatigue_upper": 0.44451496814785885, "lower_improvement": -0.34387990810946356, "mode": "repair", "provider_disparity_upper": 0.1183101851851851, "relevance_delta_lower": -0.015074180616582944}
2026-08-18 02:54:16,593 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "novel_slot", "provider_balance"], "coalition_mask": 55, "cost": 0.43, "fatigue_upper": 0.0, "lower_improvement": -0.09138135872160963, "mode": "repair", "provider_disparity_upper": 0.1216049382716049, "relevance_delta_lower": -0.046314952536664844}
2026-08-18 02:54:16,593 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 58, "cost": 0.36, "fatigue_upper": 0.43790742449355374, "lower_improvement": -0.31937148722203307, "mode": "repair", "provider_disparity_upper": 0.09783179012345666, "relevance_delta_lower": -0.02257069381127974}
2026-08-18 02:54:16,593 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 59, "cost": 0.41000000000000003, "fatigue_upper": 0.0, "lower_improvement": -0.07070040385169651, "mode": "repair", "provider_disparity_upper": 0.11020833333333324, "relevance_delta_lower": -0.046721314901966626}
2026-08-18 02:54:16,594 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 61, "cost": 0.39, "fatigue_upper": 0.0, "lower_improvement": -0.052472194805534444, "mode": "repair", "provider_disparity_upper": 0.12075617283950613, "relevance_delta_lower": -0.04453998042091023}
2026-08-18 02:54:16,594 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 62, "cost": 0.44, "fatigue_upper": 0.44378770693723096, "lower_improvement": -0.4016613204412753, "mode": "repair", "provider_disparity_upper": 0.09979938271604927, "relevance_delta_lower": -0.01670951684908817}
2026-08-18 02:54:16,595 | INFO | portfolio_rejected | {"active_interventions": ["repeat_cap", "explore_slot", "tail_slot", "diversify", "novel_slot", "provider_balance"], "coalition_mask": 63, "cost": 0.49, "fatigue_upper": 0.0, "lower_improvement": -0.14967361174618043, "mode": "repair", "provider_disparity_upper": 0.11733024691358018, "relevance_delta_lower": -0.04420629494664963}
2026-08-18 02:54:16,595 | INFO | portfolio_selected | {"action": "repair_selected", "base_feasible": false, "cost": 0.11, "fatigue_upper": 0.0, "feasible": true, "lower_improvement": 0.23465266515948313, "mode": "repair", "provider_disparity_upper": 0.23436728395061723, "reason": "Base policy violates robust constraints; selected the best feasible repair by maximin improvement.", "relevance_delta_lower": -0.040973893770779535, "selected_interventions": ["repeat_cap", "diversify"], "selected_mask": 9, "status": "repair_selected", "upper_improvement": 0.2525623871874546}
2026-08-18 02:54:16,597 | INFO | explanation_card_written | {"selected_mask": 9, "status": "repair_selected"}
2026-08-18 02:54:16,597 | INFO | robust_planning_completed | {"duration_seconds": 0.018613124964758754}
2026-08-18 02:54:16,603 | INFO | reporting_started | {}
2026-08-18 02:54:16,992 | INFO | assets_generated | {"figures": ["figures/figure_01_framework.png", "figures/figure_02_shapley_regions.png", "figures/figure_03_uncertainty_widths.png", "figures/figure_04_interaction_heatmap.png", "figures/figure_05_trajectory_comparison.png", "figures/figure_06_decision_card.png", "figures/figure_07_runtime_by_cardinality.png", "figures/figure_08_scenario_sensitivity.png"], "tables": ["tables/table_01_asset_registry.csv", "tables/table_02_benchmark_configuration.csv", "tables/table_03_attribution_regions.csv", "tables/table_04_uncertainty_summary.csv", "tables/table_05_portfolio_decision.csv", "tables/table_06_long_term_tradeoffs.csv", "tables/table_07_selection_comparison.csv", "tables/table_08_runtime_summary.csv"]}
2026-08-18 02:54:16,993 | INFO | reporting_completed | {"duration_seconds": 0.39550858398433775}
2026-08-18 02:54:16,993 | INFO | run_finished | {"run_dir": "/Users/mlouhichi/Desktop/CURE-Rec/next-paper/paper-ideas/CURE-Rec/code/runs/reviewer-closure/frontier-strict_provider-20260818T014149Z-0d8d0944", "status": "completed"}
2026-08-18 02:54:16,997 | INFO | run_started | {"config_hash": "149766418503fb0a", "run_id": "frontier-baseline-20260818T015416Z-d4688d18"}
2026-08-18 02:54:16,997 | INFO | exact_game_started | {}
2026-08-18 02:54:16,998 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "nominal"}
2026-08-18 02:56:56,594 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13323832372399413, "scenario": "nominal", "shapley_efficiency_gap": 1.3877787807814457e-16}
2026-08-18 02:56:56,595 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "fatigue_stress"}
2026-08-18 02:59:34,686 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.13544545518030754, "scenario": "fatigue_stress", "shapley_efficiency_gap": 0.0}
2026-08-18 02:59:34,687 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "popularity_stress"}
2026-08-18 03:02:12,764 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.14967361174618043, "scenario": "popularity_stress", "shapley_efficiency_gap": -2.7755575615628914e-17}
2026-08-18 03:02:12,765 | INFO | simulator_ready | {"horizon": 12, "n_items": 240, "n_users": 120, "scenario": "mixed_stress"}
2026-08-18 03:04:50,497 | INFO | scenario_game_completed | {"grand_coalition_improvement": -0.14445613014573144, "scenario": "mixed_stress", "shapley_efficiency_gap": 0.0}
2026-08-18 03:04:50,502 | INFO | robust_game_completed | {"robust_grand_improvement": -0.14967361174618043, "robust_shapley_efficiency_gap": 0.0}
2026-08-18 03:04:50,505 | INFO | exact_game_completed | {"duration_seconds": 633.5057632500539}
2026-08-18 03:04:50,505 | INFO | robust_planning_started | {}
2026-08-18 03:04:50,506 | INFO | planner_mode_resolved | {"base_feasible": false, "base_lower_improvement": 0.0, "cost": 0.0, "fatigue_upper": 0.49824230098806155, "mode": "repair", "provider_disparity_upper": 0.3151543209876544, "relevance_delta_lower": 0.0}
2026-08-18 03:04:50,506 | INFO | portfolio_rejected | {"active_interventions": [], "coalition_mask": 0, "cost": 0.0, "fatigue_upper": 0.49824230098806155, "lower_improvement": 0.0, "mode": "repair", "provider_disparity_upper": 0.3151543209876544, "relevance_delta_lower": 0.0}
2026-08-18 03:04:50,506 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot"], "coalition_mask": 2, "cost": 0.1, "fatigue_upper": 0.46305694500486366, "lower_improvement": -0.07137712219788017, "mode": "repair", "provider_disparity_upper": 0.29288580246913587, "relevance_delta_lower": -0.007039870883891575}
2026-08-18 03:04:50,507 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot"], "coalition_mask": 4, "cost": 0.08, "fatigue_upper": 0.4648932204786902, "lower_improvement": -0.05056280822044795, "mode": "repair", "provider_disparity_upper": 0.28178240740740734, "relevance_delta_lower": -0.004837434258011197}
2026-08-18 03:04:50,507 | INFO | portfolio_rejected | {"active_interventions": ["diversify"], "coalition_mask": 8, "cost": 0.06, "fatigue_upper": 0.4934736740096391, "lower_improvement": -0.05876389131453319, "mode": "repair", "provider_disparity_upper": 0.31770833333333326, "relevance_delta_lower": -6.745981224032249e-05}
2026-08-18 03:04:50,508 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "diversify"], "coalition_mask": 10, "cost": 0.16, "fatigue_upper": 0.4665261551940821, "lower_improvement": -0.13825722665453052, "mode": "repair", "provider_disparity_upper": 0.3073842592592593, "relevance_delta_lower": -0.0060451505641295755}
2026-08-18 03:04:50,508 | INFO | portfolio_rejected | {"active_interventions": ["tail_slot", "diversify"], "coalition_mask": 12, "cost": 0.14, "fatigue_upper": 0.4715309883795782, "lower_improvement": -0.11798244648637923, "mode": "repair", "provider_disparity_upper": 0.3113734567901234, "relevance_delta_lower": -0.0029919432763102494}
2026-08-18 03:04:50,508 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "tail_slot", "diversify"], "coalition_mask": 14, "cost": 0.24, "fatigue_upper": 0.43359548337015746, "lower_improvement": -0.18848812492511985, "mode": "repair", "provider_disparity_upper": 0.28331018518518514, "relevance_delta_lower": -0.010304694831896}
2026-08-18 03:04:50,509 | INFO | portfolio_rejected | {"active_interventions": ["novel_slot"], "coalition_mask": 16, "cost": 0.08, "fatigue_upper": 0.46812137445644175, "lower_improvement": -0.0789417911423797, "mode": "repair", "provider_disparity_upper": 0.38573302469135795, "relevance_delta_lower": -0.03918691196597257}
2026-08-18 03:04:50,509 | INFO | portfolio_rejected | {"active_interventions": ["explore_slot", "novel_slot"], "coalition_mask": 18, "cost": 0.18, "fatigue_upper": 0.4286087752910208, "lower_improvement": -0.14491398030587338, "mode": "repair", "provider_disparity_upper": 0.3775077160493827, "relevance_delta_lower": -0.04588572116305478}

,setting,name,budget,relevance,provider,fatigue,portfolio,status,mode,lower_improvement,base_feasible,source_run
0,strict_provider,strict_provider,0.35,-0.08,0.24,0.65,repeat_cap;diversify,repair_selected,repair,0.234653,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...
1,baseline,baseline,0.35,-0.08,0.28,0.65,repeat_cap,repair_selected,repair,0.294495,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...
2,relaxed_provider,relaxed_provider,0.35,-0.08,0.34,0.65,repeat_cap,improve_selected,improvement,0.294495,True,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...
3,tight_budget,tight_budget,0.20,-0.08,0.28,0.65,repeat_cap,repair_selected,repair,0.294495,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...
4,tight_relevance,tight_relevance,0.35,-0.03,0.28,0.65,provider_balance,repair_selected,repair,-0.114157,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...
5,tight_fatigue,tight_fatigue,0.35,-0.08,0.28,0.45,repeat_cap,repair_selected,repair,0.294495,False,/Users/mlouhichi/Desktop/CURE-Rec/next-paper/p...

## 4. Divergent selector protocol

The primary full configuration has selector ties. This cell records the mandatory protocol: select only on calibration seeds, freeze masks, and evaluate on disjoint seeds. A full implementation must use completed game tables from configurations where masks differ; it must not treat a single dominant repeat-cap configuration as evidence of selector superiority.

In [5]:
if RUN_ALL and RUN_DIVERGENT_SELECTOR:
 print('Divergent-selector action requires archived configurations with different masks; primary tied result is retained as a null comparison.')
 print('Required output columns: configuration, selector, selection_seed, evaluation_seed, frozen_mask, robust_regret, feasible, constraint margins.')
else: print('Divergent selector protocol skipped.')

Divergent-selector action requires archived configurations with different masks; primary tied result is retained as a null comparison.
Required output columns: configuration, selector, selection_seed, evaluation_seed, frozen_mask, robust_regret, feasible, constraint margins.

## 5. Semi-real intervention validation

In [6]:
if RUN_SEMI_REAL:
 raise NotImplementedError('Requires audited replay/world-model intervention semantics; no unsupported real intervention claim is generated.')
else: print('Semi-real intervention validation skipped: audited intervention log/world model unavailable.')

Semi-real intervention validation skipped: audited intervention log/world model unavailable.

## 6. Integrated 8/10-player scaling

In [7]:
if RUN_INTEGRATED_SCALING:
 raise NotImplementedError('Distinct 8/10-player policy operators must be integrated into CURE-Sim before this study can run.')
else: print('Integrated scaling skipped: current 8/10 result is arithmetic attribution stress testing only.')

Integrated scaling skipped: current 8/10 result is arithmetic attribution stress testing only.

In [8]:
out=RESULTS/'reviewer_closure'; out.mkdir(parents=True,exist_ok=True)
manifest={'run_all':RUN_ALL,'utility_sensitivity':'executed' if RUN_UTILITY_SENSITIVITY else 'skipped','constraint_frontier':'executed' if RUN_CONSTRAINT_FRONTIER else 'skipped','divergent_selector':'protocol_only_primary_tie_retained','semi_real':'skipped_no_audited_intervention_data','integrated_scaling':'skipped_no_integrated_8_10_operators','yaml_changed':False}
(out/'closure_manifest.json').write_text(json.dumps(manifest,indent=2)); print(json.dumps(manifest,indent=2))

{
  "run_all": true,
  "utility_sensitivity": "executed",
  "constraint_frontier": "executed",
  "divergent_selector": "protocol_only_primary_tie_retained",
  "semi_real": "skipped_no_audited_intervention_data",
  "integrated_scaling": "skipped_no_integrated_8_10_operators",
  "yaml_changed": false
}